export type PackageOption = {
  id: string;
  title: string;
  type?: string | null;
  display_price?: string | number | null;
  total_credits?: number | null;
  duration_days?: number | null;
  capacity?: number | null;
  summary?: string | null;
  rules?: Record<string, unknown> | null;
  service_key?: string | null;
  service_name?: string | null;
  lesson_category?: string | null;
  weekly_class_hours?: number | null;
  required_preference_slots?: number | null;
  required_trainer_free_slots?: number | null;
  is_available?: boolean;
  unavailable_reason?: string | null;
  lesson_mode?: string | null;
  sub_lessons?: string[];
  session_duration_minutes?: number | null;
  break_duration_minutes?: number | null;
  allow_member_multi_select?: boolean;
  allow_drop_in_booking?: boolean;
};

export type AdminPackage = {
  id: string;
  title: string;
  type: string;
  total_credits: number;
  duration_days: number;
  capacity: number;
  is_active: boolean;
  is_visible: boolean;
  is_public: boolean;
  display_price?: string | number | null;
  service_key?: string | null;
  service_name?: string | null;
  lesson_category?: string | null;
  capacity_label?: string | null;
  trainer_commission_rate?: number | null;
  commission_label?: string | null;
  pricing_label?: string | null;
  summary?: string | null;
  rules?: Record<string, unknown> | null;
  lesson_mode?: string | null;
  sub_lessons?: string[];
  linked_group_class_ids?: string[];
  linked_group_class_titles?: string[];
  session_duration_minutes?: number | null;
  break_duration_minutes?: number | null;
  allow_member_multi_select?: boolean;
  allow_drop_in_booking?: boolean;
};
