// Bu paylasilan UI component'i mobil tasarim sistemindeki app icon.registry parcasi icin standart gorunum saglar.
// Farkli ekranlarda ayni stil ve etkileşim dilini korumak icin bu katmanda tutulur.
import type { LucideIcon } from "lucide-react-native";
import {
  Bell,
  Building2,
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  CheckCheck,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  CreditCard,
  ContactRound,
  Gift,
  Percent,
  House,
  LayoutGrid,
  LogOut,
  Mail,
  MapPin,
  Droplets,
  NotebookPen,
  PackageOpen,
  Phone,
  TurkishLira,
  QrCode,
  Ruler,
  ScanLine,
  Search,
  Settings2,
  Shield,
  Sparkles,
  Star,
  Stethoscope,
  Target,
  Ticket,
  TrendingUp,
  TriangleAlert,
  UserRound,
  Users,
  Download,
  Wallet,
  Weight,
  Dumbbell,
  HeartPulse,
  UsersRound,
} from "lucide-react-native";
import { APP_ICON_NAMES, type AppIconName } from "./app-icon.names";

export const APP_ICON_COMPONENTS: Record<AppIconName, LucideIcon> = {
  "arrow-left": ChevronLeft,
  "arrow-right": ChevronRight,
  home: House,
  calendar: CalendarDays,
  package: PackageOpen,
  progress: TrendingUp,
  profile: UserRound,
  today: Clock3,
  members: Users,
  checkin: ClipboardCheck,
  earnings: Wallet,
  dashboard: LayoutGrid,
  approvals: CheckCheck,
  notifications: Bell,
  trainer: Stethoscope,
  member: ContactRound,
  request: ClipboardList,
  wallet: CreditCard,
  gift: Gift,
  ticket: Ticket,
  ruler: Ruler,
  shield: Shield,
  scan: ScanLine,
  qr: QrCode,
  risk: TriangleAlert,
  salon: Building2,
  spark: Sparkles,
  logout: LogOut,
  clients: Users,
  measurements: HeartPulse,
  referral: Gift,
  settings: Settings2,
  location: MapPin,
  phone: Phone,
  email: Mail,
  clock: Clock3,
  notes: NotebookPen,
  campaigns: Gift,
  subscription: CreditCard,
  percent: Percent,
  pricing: Wallet,
  clinic: Building2,
  target: Target,
  search: Search,
  premium: Star,
  weight: Weight,
  droplets: Droplets,
  dumbbell: Dumbbell,
  money: TurkishLira,
  download: Download,
  usersRound: UsersRound,
};

void APP_ICON_NAMES;