// Bu paylasilan UI component'i mobil tasarim sistemindeki app icon.names parcasi icin standart gorunum saglar.
// Farkli ekranlarda ayni stil ve etkileşim dilini korumak icin bu katmanda tutulur.
export const APP_ICON_NAMES = [
  "arrow-left",
  "arrow-right",
  "home",
  "calendar",
  "package",
  "progress",
  "profile",
  "today",
  "members",
  "checkin",
  "earnings",
  "dashboard",
  "approvals",
  "notifications",
  "trainer",
  "member",
  "request",
  "wallet",
  "gift",
  "ticket",
  "ruler",
  "shield",
  "scan",
  "qr",
  "risk",
  "salon",
  "spark",
  "logout",
  "clients",
  "measurements",
  "money",
  "referral",
  "settings",
  "location",
  "phone",
  "email",
  "clock",
  "notes",
  "campaigns",
  "subscription",
  "pricing",
  "clinic",
  "target",
  "search",
  "premium",
  "weight",
  "droplets",
  "dumbbell",
  "percent",
  "download",
  "external",
  "copy",
  "usersRound",
] as const;

export type AppIconName = (typeof APP_ICON_NAMES)[number];
