// Tasarim token'lari renk, bosluk, tipografi ve boyut kararlarini tek merkezde toplar.
// Mobil arayuzun tutarli kalmasi icin component'ler ham sayilar yerine bu sabitleri kullanir.
export const tokens = {
  colors: {
    background: "#F8FAFB",
    backgroundStrong: "#EEF6F0",
    surface: "#FFFFFF",
    surfaceSoft: "#F2F8F3",
    surfaceRaised: "#FFFFFF",
    border: "#E1EADF",
    borderStrong: "#AFC7B2",
    text: "#1F2937",
    textMuted: "#6B7280",
    primary: "#97BB9C",
    primaryStrong: "#6F9274",
    primarySoft: "#F4F9F4",
    success: "#22C55E",
    successSoft: "#EAF8EF",
    danger: "#EF4444",
    warning: "#F59E0B",
    warningSoft: "#FEF3C7",
    infoSoft: "#EEF7FC",
    trustBlue: "#5DADE2",
    premium: "#7C3AED",
    overlay: "rgba(15, 23, 42, 0.22)",
    shadow: "#0F172A",
  },
  gradient: {
    heroTop: "#FFFFFF",
    heroBottom: "#EDF5EE",
    brand: ["#97BB9C", "#C7DAC9"] as const,
    panel: ["rgba(151,187,156,0.14)", "rgba(199,218,201,0.10)"] as const,
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 20,
    xl: 24,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 32,
  },
  font: {
    xs: 12,
    sm: 15,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 24,
    display: 28,
  },
  fontFamily: {
    light: "Poppins-Light",
    regular: "Poppins-Regular",
    medium: "Poppins-Medium",
    semibold: "Poppins-SemiBold",
    bold: "Poppins-Bold",
  },
  lineHeight: {
    compact: 18,
    normal: 22,
    relaxed: 26,
  },
  touch: {
    min: 44,
    comfortable: 52,
    heroButton: 56,
  },
  shadow: {
    soft: {
      shadowColor: "#0F172A",
      shadowOpacity: 0.06,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 8 },
      elevation: 3,
    },
    focus: {
      shadowColor: "#97BB9C",
      shadowOpacity: 0.14,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 4,
    },
    float: {
      shadowColor: "#0F172A",
      shadowOpacity: 0.1,
      shadowRadius: 28,
      shadowOffset: { width: 0, height: 18 },
      elevation: 6,
    },
  },
};

export type Tokens = typeof tokens;
